import { CELO_DERIVATION_PATH_BASE, ETHEREUM_DERIVATION_PATH } from '@celo/base'

export const CIP64_PREFIX = '0x7b'
export const CELO_BASE_DERIVATION_PATH = `${CELO_DERIVATION_PATH_BASE.slice(2)}/0`
export const DEFAULT_DERIVATION_PATH = `${ETHEREUM_DERIVATION_PATH.slice(2)}/0`
