name: Bug report
description: File a bug report
labels: ["bug report"]
body:
    - type: markdown
      attributes:
          value: |
              Please ensure that the bug has not already been filed in the issue tracker.

              Thanks for taking the time to report this bug!
    - type: dropdown
      attributes:
          label: Package
          description: What package is the bug in?
          multiple: true
          options:
              - '@celo/celocli'
              - '@celo/contractkit'
              - '@celo/base'
              - '@celo/connect'
              - '@celo/wallet-...'
              - Other (please describe)
      validations:
          required: true
    - type: checkboxes
      attributes:
          label: Have you ensured that all of these are up to date?
          options:
              - label: the package you are using
    - type: input
      attributes:
          label: What version of the package are you on?
          description: |
            For local installations, run: `npm list <package-name>`
            For global installations, run: `npm list -g <package-name>`
          placeholder: "Run command above and paste the output here"
    - type: input
      attributes:
          label: What command or function is the bug in?
          description: Leave empty if not relevant
          placeholder: "For example: `celocli releasecelo:show`"
    - type: dropdown
      attributes:
          label: Operating System
          description: What operating system are you on?
          options:
              - Windows
              - macOS (Intel)
              - macOS (Apple Silicon)
              - Linux
    - type: textarea
      attributes:
          label: Describe the bug
          description: Please include relevant code snippets, terminal output, and screenshots if relevant.
      validations:
          required: true