name: Feature request
description: Suggest a feature
labels: ["feature request"]
body:
    - type: markdown
      attributes:
          value: |
              Please ensure that the feature has not already been requested in the issue tracker.

              Thanks for helping us improve Celo packages!
    - type: dropdown
      attributes:
          label: Component
          description: What package is the feature for?
          multiple: true
          options:
              - '@celo/celocli'
              - '@celo/contractkit'
              - '@celo/base'
              - '@celo/connect'
              - '@celo/wallet-...'
              - Other (please describe)
      validations:
          required: true
    - type: textarea
      attributes:
          label: Describe the feature you would like
          description: Please also describe what the feature is aiming to solve, if relevant.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Additional context
          description: Add any other context to the feature (like screenshots, code snippets, resources)