name: Deprecate Packages

on: 
  workflow_dispatch:
    inputs:
      maxVersion: 
        description: "Any version less than this will be marked"
        required: true
        type: string
      package: 
        description:  "Name of Package e.g. @celo/base"
        required: true
        type: string
      message:  
        description: "Message to be displayed to users using deprecated version"
        required: true
        type: string
      dryRun:
        type: boolean
        description: Actually run?
        default: false
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  sunset:
    name: Deprecate All versions of ${{inputs.package}} prior to ${{inputs.version}}
    runs-on: ['self-hosted', 'org', 'npm-publish']
    permissions:
      id-token: write
    steps:
      - name: Akeyless Get Secrets
        id: get_auth_token
        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/NPM/npm-publish-token":"NPM_TOKEN"}'
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Check npm version
        run: |
          npm --version
          echo will deprecate ${{inputs.package}}@"< ${{inputs.version}}" "${{message}}"
      - name: Run Deprecate Command
        if: inputs.dryRun == 'false'
        run: npm deprecate ${{inputs.package}}@"< ${{inputs.version}}" "${{message}}"
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}