name: Workflow for Codecov Testing
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Akeyless Get Secrets
        id: get_codecov_token
        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/dev-tooling-circle/codecov/developer-tooling":"CODECOV_TOKEN"}'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ env.CODECOV_TOKEN }}
